### ISSUE TITLE
Auto Elevate Tokens prevents manual changes to elevation

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#105] opened 2024-01-06 19:55 UTC
While Auto Elevate Tokens is turned on you are unable to use the UI to change the elevation of any token on the scene even if the token isn't on any elevation at all.

I tested this by moving a token onto a 50ft elevation. Then when I moved him off, it didn't automatically go down and also I was unable to manually lower it to 0 using the UI.

![image](https://github.com/caewok/fvtt-elevated-vision/assets/12570777/b352d4c2-57de-475c-a857-544ec2bbb59c)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/12570777/e6e0bffd-a2ec-4ca6-a572-9b46ca895288)

**Comment by Larkinabout** [comment] 2024-01-15 17:20
This seems to be an interaction with the 'Elevated Tokens Fly' toggle. While toggled on, when moving a token to a higher elevation and them back, it will stay at the same high elevation. This is most likely as intended. However, trying to manually set the token to the elevation of its current position fails, whereas, I suggest, users would expect it to succeed. Ideally, I think, the `endingElevation` needs to be set to an elevation equal to the current position or higher based on what is manually entered. For example, if the token is 40', the elevation of the current position is 20', if the user manually enters 25' it should change their elevation to 25'. If the user manually enters 0' it should change their elevation to 20'.

**Comment by Larkinabout** [comment] 2024-01-15 21:42
Upon further inspection, the issue of not being able to manually alter elevation is also still there when 'Elevated Token Fly' is toggled off.

Could it allow for manual alteration where the elevation is above the layer elevation of the current position? Perhaps as an optional setting. And perhaps another optional setting to test for flight only where the token elevation is at least 1 foot above the layer elevation prior to movement? This would then allow for the assumption that tokens with an elevation matching the layer elevation prior to movement are in fact standing on the ground.

**Comment by caewok** [comment] 2024-02-19 15:19
Shoudl be fixed in v0.5.13. Thanks!

**Closed by caewok** 2024-02-19 15:19 UTC
